version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: kami
    ports:
      - "5432:5432"
    restart: always